version: '3.8'

services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariaDB/
      dockerfile: Dockerfile
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    networks:
      - inception
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress/
      dockerfile: Dockerfile
    restart: always
    networks:
      - inception
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html

  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build:
      context: ./requirements/ngnix/
      dockerfile: Dockerfile
    networks:
      - inception
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/esekouni/data/wordpress_database
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/esekouni/data/mariadb_database

networks:
  inception:
    name: inception
    driver: bridge
